apiVersion: v1
kind: ServiceAccount
metadata:
  name: gates-fronter
  namespace: gates
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gates-fronter-rbac
subjects:
  - kind: ServiceAccount
    name: gates-fronter
    namespace: gates
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io